Develop generate schedules filters
colinaguan/enrollable pull request #11
Opened 2021-02-15 20:45 UTC by yzhao179

2021-02-15 20:56 UTC, jshen1s1 requested changes
several commits behind the main branch 
merging will cause errors

2021-02-16 05:52 UTC, colinaguan requested changes
The branch isn't up to date with the main; some file contents are completely replaced by old commits. If we merge this as is, it will be very problematic. Remember that what is in this branch should be a full working product off of what we already have. If the changes are too deep, just take your work, put it in a GenerateFilters.js file in local, make a new branch off of the updated main branch, and re-add your component to the GenerateSchedulesPage.js file.

Spacing and readability could be better.

Any and all warnings should be fixed (unused variables, etc.)

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +                            onChange={setMax(this.target.value())}
(e) => setMax(e.target.value)

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +                                onChange={setMin(this.target.value())}
(e) => setMin(e.target.value)

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/CardSample.tsx
> +import React from 'react';
if this file isn't needed, delete

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/ClassSearchFilters.js
> +import React from 'react';
not up to date

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/LoginPage.js
> +import React from 'react';
not up to date

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +const useStyles = makeStyles((theme) => ({
why not use a css file?

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +        if(maxUnit>19||minUnit>19||maxUnit<12||minUnit<12||maxUnit<minUnit)
units should be allowed to exceed 19

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +export default function GenerateSchedulesUnitAndTimePicker() {
(note for later reference) setting minimum units, maximum units, and time constraints will be passed as props

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +                    <form className={classes.root} noValidate autoComplete="off">
if this is the bootstrap Form component, should be capitalized

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +type="submit"
fix indentation

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +        </>
this outer element isn't needed if the whole thing is wrapped in a component (row or container)

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +<Row>
fix indentation

2021-02-16 05:52 UTC, colinaguan commented on frontend/src/components/GenerateSchedulesUnitAndTimePicker.js
> +                <Row>
The whole filters component should be a form, so you can use Form.Row and Form.Col elements. Having each filter element be its own form isn't the best solution.

2021-02-17 22:04 UTC, Brenden-Greenlee approved these changes

2021-02-19 06:04 UTC, colinaguan commented
filters work has been moved to another branch

2021-02-19 06:04 UTC, closed without merging