modified question mark query
colinaguan/enrollable pull request #9
Opened 2021-02-09 00:17 UTC by jshen1s1

for all filters: /api/department?dep=any&type=any&ge=any
for single class: /api/course?course=XX

2021-02-12 05:38 UTC, colinaguan reviewed
always use === and !== in javascript

2021-02-12 23:15 UTC, colinaguan requested changes
there's a lot of != and == in here (only commented on a few) but just make sure all of them are replaced

one of the reasons why javascript is annoying is because == vs. === can be the difference between a space shuttle crashing into the moon or landing successfully... yay javascript

2021-02-12 23:15 UTC, colinaguan commented on backend/routes/department.js
> +            if (classData[i][j].type == queryParameter.type.toUpperCase()){
=== in javascript

2021-02-12 23:15 UTC, colinaguan commented on backend/routes/department.js
> +                        if (classData[i][j].ge[k] == queryParameter.ge.toUpperCase()){
===

2021-02-12 23:15 UTC, colinaguan commented on backend/routes/department.js
> +                  if (classData[i][j].ge[k] == queryParameter.ge.toUpperCase()){
===

2021-02-12 23:15 UTC, colinaguan commented on backend/routes/course.js
>      if (Object.keys(req.query).length != 0) {
!==

2021-02-15 20:33 UTC, colinaguan approved these changes

2021-02-15 20:44 UTC, Brenden-Greenlee approved these changes

2021-02-15 21:04 UTC, merged